/**
 * lib/openapi/slice.test.ts
 * Run with: npx tsx --test lib/openapi/slice.test.ts
 */

import { test } from "node:test";
import { strict as assert } from "node:assert";
import {
  buildThemedSchema,
  makeOperationId,
  parseRef,
  pickReferencedComponents,
} from "./slice";
import type { SourceSwagger } from "../catalog/types";
import type { ResolvedTheme } from "../themes/registry";

const FAKE_THEMES: Record<string, ResolvedTheme> = {
  members: {
    key: "members",
    title: "Members",
    description: "members",
    tags: ["Members"],
    allowedMethods: ["GET", "POST"],
    triggers: [],
    exposeToVivi: true,
    autoGenerated: false,
    operationCount: 3,
  },
  authOnly: {
    key: "authOnly",
    title: "Auth",
    description: "auth",
    tags: ["Auth"],
    allowedMethods: ["POST"],
    triggers: [],
    exposeToVivi: true,
    autoGenerated: false,
    operationCount: 1,
  },
};

function fakeSwagger(): SourceSwagger {
  return {
    openapi: "3.0.4",
    info: { title: "Fake", version: "1" },
    paths: {
      "/api/Members/get": {
        post: {
          tags: ["Members"],
          summary: "Get member",
          requestBody: {
            content: {
              "application/json": {
                schema: { $ref: "#/components/schemas/MemberQuery" },
              },
            },
          },
          responses: {
            "200": {
              description: "ok",
              content: {
                "application/json": {
                  schema: { $ref: "#/components/schemas/Member" },
                },
              },
            },
          },
        },
        get: {
          tags: ["Members"],
          summary: "List members",
          responses: { "200": { description: "ok" } },
        },
      },
      "/api/Auth/Login": {
        post: {
          tags: ["Auth"],
          summary: "Login",
          requestBody: {
            content: {
              "application/json": {
                schema: { $ref: "#/components/schemas/Credentials" },
              },
            },
          },
          responses: { "200": { description: "ok" } },
        },
      },
      "/api/Members/dangerous": {
        delete: {
          tags: ["Members"],
          summary: "Delete member",
          responses: { "200": { description: "ok" } },
        },
      },
      "/api/Untagged": {
        post: {
          summary: "Untagged",
          responses: { "200": { description: "ok" } },
        },
      },
    },
    components: {
      schemas: {
        Member: {
          type: "object",
          properties: {
            id: { type: "string" },
            address: { $ref: "#/components/schemas/Address" },
            spouse: { $ref: "#/components/schemas/Member" }, // self-ref
          },
        },
        Address: {
          type: "object",
          properties: { country: { $ref: "#/components/schemas/Country" } },
        },
        Country: {
          type: "object",
          properties: { code: { type: "string" } },
        },
        MemberQuery: { type: "object", properties: { id: { type: "string" } } },
        Credentials: {
          type: "object",
          properties: { username: { type: "string" }, password: { type: "string" } },
        },
        Unrelated: { type: "object" },
      },
      securitySchemes: {
        Bearer: { type: "http", scheme: "bearer", bearerFormat: "JWT" },
      },
    },
  };
}

test("makeOperationId generates expected format", () => {
  assert.equal(
    makeOperationId("Request", "POST", "/api/Request/CreateRequest"),
    "Request_POST_api_Request_CreateRequest",
  );
  assert.equal(makeOperationId("AppUser", "POST", "/Login"), "AppUser_POST_Login");
});

test("parseRef parses #/components/<section>/<name>", () => {
  assert.deepEqual(parseRef("#/components/schemas/Foo"), {
    section: "schemas",
    name: "Foo",
  });
  assert.equal(parseRef("not-a-ref"), null);
});

test("buildThemedSchema filters by tag and method", () => {
  const themed = buildThemedSchema("members", fakeSwagger(), FAKE_THEMES);
  assert.ok(themed.paths["/api/Members/get"]?.post);
  assert.ok(themed.paths["/api/Members/get"]?.get);
  assert.ok(!themed.paths["/api/Members/dangerous"]);
  assert.ok(!themed.paths["/api/Auth/Login"]);
  assert.ok(!themed.paths["/api/Untagged"]);
});

test("buildThemedSchema injects deterministic operationId", () => {
  const themed = buildThemedSchema("members", fakeSwagger(), FAKE_THEMES);
  assert.equal(
    themed.paths["/api/Members/get"].post.operationId,
    "Members_POST_api_Members_get",
  );
});

test("buildThemedSchema injects servers (default + override)", () => {
  const t1 = buildThemedSchema("members", fakeSwagger(), FAKE_THEMES);
  assert.deepEqual(t1.servers, [{ url: "https://pprvmw.com" }]);
  const t2 = buildThemedSchema("members", fakeSwagger(), FAKE_THEMES, {
    serverUrl: "https://example.test",
  });
  assert.deepEqual(t2.servers, [{ url: "https://example.test" }]);
});

test("buildThemedSchema walks $ref graph recursively (transitive + circular)", () => {
  const themed = buildThemedSchema("members", fakeSwagger(), FAKE_THEMES);
  const schemas = themed.components.schemas as Record<string, unknown>;
  assert.ok(schemas.Member, "Member should be included");
  assert.ok(schemas.MemberQuery, "MemberQuery should be included");
  assert.ok(schemas.Address, "Address should be included transitively");
  assert.ok(schemas.Country, "Country should be included transitively");
  assert.ok(!schemas.Unrelated, "Unrelated must not leak in");
});

test("buildThemedSchema preserves securitySchemes always", () => {
  const themed = buildThemedSchema("members", fakeSwagger(), FAKE_THEMES);
  const sec = themed.components.securitySchemes as Record<string, unknown>;
  assert.ok(sec?.Bearer);
});

test("buildThemedSchema isolates themes (auth slice excludes member schemas)", () => {
  const themed = buildThemedSchema("authOnly", fakeSwagger(), FAKE_THEMES);
  assert.ok(themed.paths["/api/Auth/Login"]?.post);
  assert.ok(!themed.paths["/api/Members/get"]);
  const schemas = themed.components.schemas as Record<string, unknown>;
  assert.ok(schemas?.Credentials);
  assert.ok(!schemas?.Member);
});

test("buildThemedSchema throws on unknown theme", () => {
  assert.throws(
    () => buildThemedSchema("does-not-exist", fakeSwagger(), FAKE_THEMES),
    /Unknown theme/,
  );
});

test("pickReferencedComponents returns empty when components missing", () => {
  const out = pickReferencedComponents(undefined, [{ $ref: "#/components/schemas/X" }]);
  assert.deepEqual(out, {});
});
