"use client";

import { useState, useTransition } from "react";

export interface ThemeRow {
  key: string;
  title: string;
  description: string;
  sourceTags: string[];
  allowedMethods: string[];
  operationCount: number;
  autoGenerated: boolean;
  hidden: boolean;
  schemaUrl: string;
}

export interface DashboardMeta {
  lastFetched: string;
  swaggerUrl: string;
  sourceTitle: string;
  sourceVersion: string;
  totalEndpoints: number;
  totalThemes: number;
  visibleThemes: number;
  themes: ThemeRow[];
}

interface Props {
  meta: DashboardMeta;
  refreshAction: () => Promise<void>;
}

function fmtTime(iso: string): string {
  const d = new Date(iso);
  return d.toLocaleString(undefined, {
    year: "numeric",
    month: "short",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
  });
}

function relative(iso: string): string {
  const ms = Date.now() - new Date(iso).getTime();
  const s = Math.floor(ms / 1000);
  if (s < 60) return `${s}s ago`;
  const m = Math.floor(s / 60);
  if (m < 60) return `${m}m ago`;
  const h = Math.floor(m / 60);
  if (h < 24) return `${h}h ago`;
  const d = Math.floor(h / 24);
  return `${d}d ago`;
}

export function DashboardClient({ meta, refreshAction }: Props) {
  const [refreshing, startRefreshing] = useTransition();
  const [copied, setCopied] = useState<string | null>(null);
  const [promptCopying, setPromptCopying] = useState(false);
  const [promptPreview, setPromptPreview] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  function refresh() {
    setError(null);
    startRefreshing(async () => {
      try {
        await refreshAction();
      } catch (e) {
        setError(e instanceof Error ? e.message : String(e));
      }
    });
  }

  async function copyText(text: string, label: string) {
    try {
      await navigator.clipboard.writeText(text);
      setCopied(label);
      setTimeout(() => setCopied(null), 1500);
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
    }
  }

  async function copySystemPrompt() {
    setError(null);
    setPromptCopying(true);
    try {
      const r = await fetch("/system-prompt", { cache: "no-store" });
      if (!r.ok) throw new Error(`HTTP ${r.status}`);
      const text = await r.text();
      await navigator.clipboard.writeText(text);
      setCopied("system-prompt");
      setPromptPreview(text);
      setTimeout(() => setCopied(null), 2000);
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
    } finally {
      setPromptCopying(false);
    }
  }

  const baseUrl = typeof window !== "undefined" ? window.location.origin : "";

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100">
      <div className="mx-auto max-w-6xl px-6 py-10">
        <header className="flex flex-wrap items-start justify-between gap-4">
          <div>
            <h1 className="text-3xl font-bold tracking-tight">VIVI Themed OpenAPI</h1>
            <p className="mt-1 text-slate-400">
              Slices the source swagger into themed OpenAPI schemas for VIVI.
            </p>
          </div>
          <div className="flex flex-wrap gap-2">
            <button
              onClick={copySystemPrompt}
              disabled={promptCopying || refreshing}
              className="rounded-lg bg-slate-700 px-4 py-2 font-medium text-slate-100 shadow hover:bg-slate-600 disabled:cursor-not-allowed disabled:opacity-50"
              title="Generates the latest VIVI agent system prompt and copies it to your clipboard."
            >
              {copied === "system-prompt"
                ? "Prompt copied ✓"
                : promptCopying
                  ? "Generating…"
                  : "Copy system prompt"}
            </button>
            <button
              onClick={refresh}
              disabled={refreshing || promptCopying}
              className="rounded-lg bg-emerald-500 px-4 py-2 font-medium text-slate-900 shadow hover:bg-emerald-400 disabled:cursor-not-allowed disabled:opacity-50"
            >
              {refreshing ? "Refreshing…" : "Refresh from source"}
            </button>
          </div>
        </header>

        {error && (
          <div className="mt-6 rounded-lg border border-red-500/40 bg-red-500/10 px-4 py-3 text-red-200">
            <strong>Error:</strong> {error}
          </div>
        )}

        <section className="mt-8 grid grid-cols-2 gap-4 sm:grid-cols-4">
          <Stat
            label="Source"
            value={meta.sourceTitle}
            sub={meta.sourceVersion ? `v${meta.sourceVersion}` : undefined}
          />
          <Stat label="Endpoints" value={String(meta.totalEndpoints)} />
          <Stat
            label="Themes"
            value={String(meta.visibleThemes)}
            sub={`${meta.totalThemes} total`}
          />
          <Stat
            label="Last refresh"
            value={relative(meta.lastFetched)}
            sub={fmtTime(meta.lastFetched)}
          />
        </section>

        <div className="mt-4 flex flex-wrap items-center gap-3 text-sm">
          <span className="text-slate-400">Source URL:</span>
          <code className="rounded bg-slate-800 px-2 py-1 text-xs text-slate-200">
            {meta.swaggerUrl}
          </code>
          <a href="/themes" className="text-emerald-400 hover:text-emerald-300" target="_blank" rel="noopener noreferrer">
            /themes JSON
          </a>
          <a href="/system-prompt" className="text-emerald-400 hover:text-emerald-300" target="_blank" rel="noopener noreferrer">
            /system-prompt
          </a>
          <a href="/health" className="text-emerald-400 hover:text-emerald-300" target="_blank" rel="noopener noreferrer">
            /health
          </a>
        </div>

        <h2 className="mt-10 text-xl font-semibold">Themes ({meta.themes.length})</h2>
        <p className="mt-1 text-sm text-slate-400">
          Each theme below = one Custom API integration in VIVI. Click {`"`}Copy URL{`"`} and paste it into VIVI{`'`}s {`"`}Import from URL{`"`} field.
        </p>

        <ul className="mt-4 grid gap-4 sm:grid-cols-2">
          {meta.themes.map((t) => (
            <li
              key={t.key}
              className={`rounded-xl border p-4 ${
                t.hidden ? "border-slate-800 bg-slate-900/40 opacity-60" : "border-slate-800 bg-slate-900"
              }`}
            >
              <div className="flex items-start justify-between gap-3">
                <div>
                  <h3 className="font-semibold text-slate-100">{t.title}</h3>
                  <code className="text-xs text-slate-400">{t.key}</code>
                </div>
                <span
                  className={`rounded-full px-2 py-0.5 text-xs font-medium ${
                    t.hidden
                      ? "bg-slate-700/40 text-slate-400"
                      : t.autoGenerated
                        ? "bg-amber-500/20 text-amber-300"
                        : "bg-emerald-500/20 text-emerald-300"
                  }`}
                >
                  {t.hidden ? "hidden" : t.autoGenerated ? "auto" : "curated"}
                </span>
              </div>
              <p className="mt-2 line-clamp-3 text-sm text-slate-300">{t.description}</p>
              <div className="mt-3 flex flex-wrap gap-2 text-xs">
                {t.sourceTags.map((tag) => (
                  <span key={tag} className="rounded bg-slate-800 px-2 py-0.5 text-slate-300">
                    {tag}
                  </span>
                ))}
                <span className="rounded bg-slate-800 px-2 py-0.5 text-slate-400">{t.operationCount} ops</span>
                <span className="rounded bg-slate-800 px-2 py-0.5 text-slate-400">{t.allowedMethods.join(" · ")}</span>
              </div>
              {!t.hidden && (
                <div className="mt-3 flex gap-2 text-xs">
                  <button
                    onClick={() => copyText(`${baseUrl}${t.schemaUrl}`, t.key)}
                    className="rounded bg-slate-800 px-3 py-1 text-slate-200 hover:bg-slate-700"
                  >
                    {copied === t.key ? "Copied!" : "Copy URL"}
                  </button>
                  <a
                    href={t.schemaUrl}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="rounded bg-slate-800 px-3 py-1 text-slate-200 hover:bg-slate-700"
                  >
                    Open schema
                  </a>
                </div>
              )}
            </li>
          ))}
        </ul>

        {promptPreview && (
          <details className="mt-10 rounded-xl border border-slate-800 bg-slate-900 p-4">
            <summary className="cursor-pointer text-sm font-semibold text-slate-200">
              System prompt preview ({promptPreview.length.toLocaleString()} chars) — already copied to clipboard
            </summary>
            <pre className="mt-3 max-h-96 overflow-auto rounded bg-slate-950 p-3 text-xs leading-relaxed text-slate-300">
              {promptPreview}
            </pre>
          </details>
        )}

        <footer className="mt-12 border-t border-slate-800 pt-6 text-xs text-slate-500">
          <p>
            Backend dev workflow: deploy a new endpoint or tag in pprvmw → click{" "}
            <span className="font-semibold text-slate-300">Refresh from source</span> above → new themes appear here automatically. Then click{" "}
            <span className="font-semibold text-slate-300">Copy system prompt</span> and paste into VIVI. Add new VIVI integrations only if a brand-new theme appeared.
          </p>
        </footer>
      </div>
    </div>
  );
}

function Stat({ label, value, sub }: { label: string; value: string; sub?: string }) {
  return (
    <div className="rounded-xl border border-slate-800 bg-slate-900 p-4">
      <div className="text-xs uppercase tracking-wide text-slate-500">{label}</div>
      <div className="mt-1 truncate text-lg font-semibold text-slate-100">{value}</div>
      {sub && <div className="text-xs text-slate-500">{sub}</div>}
    </div>
  );
}
