"use client";
import { useCallback, useEffect, useState } from "react";

interface Theme {
  key: string;
  title: string;
  description: string;
  sourceTags: string[];
  allowedMethods: string[];
  operationCount: number;
  autoGenerated: boolean;
  hidden: boolean;
  schemaUrl: string;
}

interface Meta {
  ok: boolean;
  lastFetched: string;
  swaggerUrl: string;
  sourceTitle: string;
  sourceVersion: string;
  totalEndpoints: number;
  totalThemes: number;
  visibleThemes: number;
  themes: Theme[];
  error?: string;
}

function fmtTime(iso: string): string {
  const d = new Date(iso);
  return d.toLocaleString(undefined, {
    year: "numeric",
    month: "short",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
  });
}

function relative(iso: string): string {
  const ms = Date.now() - new Date(iso).getTime();
  const s = Math.floor(ms / 1000);
  if (s < 60) return `${s}s ago`;
  const m = Math.floor(s / 60);
  if (m < 60) return `${m}m ago`;
  const h = Math.floor(m / 60);
  if (h < 24) return `${h}h ago`;
  const d = Math.floor(h / 24);
  return `${d}d ago`;
}

export default function Home() {
  const [meta, setMeta] = useState<Meta | null>(null);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState<string | null>(null);

  const load = useCallback(async () => {
    setError(null);
    try {
      const r = await fetch("/api/meta", { cache: "no-store" });
      const data = (await r.json()) as Meta;
      if (!data.ok) throw new Error(data.error || "Failed to load metadata");
      setMeta(data);
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
    } finally {
      setLoading(false);
    }
  }, []);

  const refresh = useCallback(async () => {
    setRefreshing(true);
    setError(null);
    try {
      const r = await fetch("/api/refresh", { method: "POST" });
      if (!r.ok) throw new Error(`Refresh failed: HTTP ${r.status}`);
      // Wait a beat for revalidation, then reload.
      await new Promise((res) => setTimeout(res, 250));
      await load();
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
    } finally {
      setRefreshing(false);
    }
  }, [load]);

  useEffect(() => {
    load();
  }, [load]);

  const baseUrl = typeof window !== "undefined" ? window.location.origin : "";

  async function copyText(text: string, label: string) {
    try {
      await navigator.clipboard.writeText(text);
      setCopied(label);
      setTimeout(() => setCopied(null), 1500);
    } catch {
      /* ignore */
    }
  }

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100">
      <div className="mx-auto max-w-6xl px-6 py-10">
        <header className="flex flex-wrap items-start justify-between gap-4">
          <div>
            <h1 className="text-3xl font-bold tracking-tight">VIVI Themed OpenAPI</h1>
            <p className="mt-1 text-slate-400">
              Slices the source swagger into themed OpenAPI schemas for VIVI.
            </p>
          </div>
          <button
            onClick={refresh}
            disabled={refreshing || loading}
            className="rounded-lg bg-emerald-500 px-4 py-2 font-medium text-slate-900 shadow hover:bg-emerald-400 disabled:cursor-not-allowed disabled:opacity-50"
          >
            {refreshing ? "Refreshing…" : "Refresh from source"}
          </button>
        </header>

        {error && (
          <div className="mt-6 rounded-lg border border-red-500/40 bg-red-500/10 px-4 py-3 text-red-200">
            <strong>Error:</strong> {error}
          </div>
        )}

        {loading && !meta && (
          <div className="mt-10 text-slate-400">Loading metadata…</div>
        )}

        {meta && (
          <>
            <section className="mt-8 grid grid-cols-2 gap-4 sm:grid-cols-4">
              <Stat label="Source" value={meta.sourceTitle ?? "—"} sub={`v${meta.sourceVersion ?? ""}`} />
              <Stat label="Endpoints" value={String(meta.totalEndpoints)} />
              <Stat
                label="Themes"
                value={String(meta.visibleThemes)}
                sub={`${meta.totalThemes} total`}
              />
              <Stat
                label="Last refresh"
                value={relative(meta.lastFetched)}
                sub={fmtTime(meta.lastFetched)}
              />
            </section>

            <div className="mt-4 flex flex-wrap items-center gap-3 text-sm">
              <span className="text-slate-400">Source URL:</span>
              <code className="rounded bg-slate-800 px-2 py-1 text-xs text-slate-200">
                {meta.swaggerUrl}
              </code>
              <a
                href="/themes"
                className="text-emerald-400 hover:text-emerald-300"
                target="_blank"
                rel="noopener noreferrer"
              >
                /themes JSON
              </a>
              <a
                href="/system-prompt"
                className="text-emerald-400 hover:text-emerald-300"
                target="_blank"
                rel="noopener noreferrer"
              >
                /system-prompt
              </a>
              <a
                href="/health"
                className="text-emerald-400 hover:text-emerald-300"
                target="_blank"
                rel="noopener noreferrer"
              >
                /health
              </a>
            </div>

            <h2 className="mt-10 text-xl font-semibold">Themes ({meta.themes.length})</h2>
            <p className="mt-1 text-sm text-slate-400">
              Each theme below = one Custom API integration in VIVI. Click "Copy URL" and paste it into VIVI's "Import from URL" field.
            </p>

            <ul className="mt-4 grid gap-4 sm:grid-cols-2">
              {meta.themes.map((t) => (
                <li
                  key={t.key}
                  className={`rounded-xl border p-4 ${
                    t.hidden
                      ? "border-slate-800 bg-slate-900/40 opacity-60"
                      : "border-slate-800 bg-slate-900"
                  }`}
                >
                  <div className="flex items-start justify-between gap-3">
                    <div>
                      <h3 className="font-semibold text-slate-100">{t.title}</h3>
                      <code className="text-xs text-slate-400">{t.key}</code>
                    </div>
                    <span
                      className={`rounded-full px-2 py-0.5 text-xs font-medium ${
                        t.hidden
                          ? "bg-slate-700/40 text-slate-400"
                          : t.autoGenerated
                            ? "bg-amber-500/20 text-amber-300"
                            : "bg-emerald-500/20 text-emerald-300"
                      }`}
                    >
                      {t.hidden ? "hidden" : t.autoGenerated ? "auto" : "curated"}
                    </span>
                  </div>
                  <p className="mt-2 line-clamp-3 text-sm text-slate-300">
                    {t.description}
                  </p>
                  <div className="mt-3 flex flex-wrap gap-2 text-xs">
                    {t.sourceTags.map((tag) => (
                      <span
                        key={tag}
                        className="rounded bg-slate-800 px-2 py-0.5 text-slate-300"
                      >
                        {tag}
                      </span>
                    ))}
                    <span className="rounded bg-slate-800 px-2 py-0.5 text-slate-400">
                      {t.operationCount} ops
                    </span>
                    <span className="rounded bg-slate-800 px-2 py-0.5 text-slate-400">
                      {t.allowedMethods.join(" · ")}
                    </span>
                  </div>
                  {!t.hidden && (
                    <div className="mt-3 flex gap-2 text-xs">
                      <button
                        onClick={() => copyText(`${baseUrl}${t.schemaUrl}`, t.key)}
                        className="rounded bg-slate-800 px-3 py-1 text-slate-200 hover:bg-slate-700"
                      >
                        {copied === t.key ? "Copied!" : "Copy URL"}
                      </button>
                      <a
                        href={t.schemaUrl}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="rounded bg-slate-800 px-3 py-1 text-slate-200 hover:bg-slate-700"
                      >
                        Open schema
                      </a>
                    </div>
                  )}
                </li>
              ))}
            </ul>

            <footer className="mt-12 border-t border-slate-800 pt-6 text-xs text-slate-500">
              <p>
                Backend dev workflow: deploy a new endpoint or tag in pprvmw → click <span className="font-semibold text-slate-300">Refresh from source</span> above → new themes appear here automatically. Re-import the affected URLs into VIVI to pick up the changes.
              </p>
            </footer>
          </>
        )}
      </div>
    </div>
  );
}

function Stat({ label, value, sub }: { label: string; value: string; sub?: string }) {
  return (
    <div className="rounded-xl border border-slate-800 bg-slate-900 p-4">
      <div className="text-xs uppercase tracking-wide text-slate-500">{label}</div>
      <div className="mt-1 truncate text-lg font-semibold text-slate-100">{value}</div>
      {sub && <div className="text-xs text-slate-500">{sub}</div>}
    </div>
  );
}
