/**
 * app/page.tsx (Server Component)
 *
 * Server-renders the dashboard. Passes environment config and initial data
 * to the client component. The client manages environment switching.
 */

import { revalidatePath, revalidateTag } from "next/cache";
import { loadCatalog, SWAGGER_CACHE_TAG, getSwaggerEnvironments } from "@/lib/catalog/runtime";
import { deriveThemes } from "@/lib/themes/registry";
import { DashboardClient, type DashboardMeta } from "./dashboard-client";

export const dynamic = "force-dynamic";

async function refreshAction(): Promise<void> {
  "use server";
  revalidateTag(SWAGGER_CACHE_TAG, "max");
  revalidatePath("/");
}

export default async function Home() {
  const cat = await loadCatalog();
  const themes = deriveThemes(cat.swagger);

  let totalOps = 0;
  for (const item of Object.values(cat.swagger.paths ?? {})) {
    if (!item) continue;
    for (const [m] of Object.entries(item)) {
      if (["get", "post", "put", "patch", "delete"].includes(m.toLowerCase())) {
        totalOps++;
      }
    }
  }

  const themeList = Object.values(themes).map((t) => ({
    key: t.key,
    title: t.title,
    description: t.description,
    sourceTags: t.tags,
    allowedMethods: t.allowedMethods,
    operationCount: t.operationCount,
    autoGenerated: t.autoGenerated,
    hidden: !t.exposeToVivi,
    schemaUrl: `/themes/${t.key}/openapi.json`,
  }));

  const meta: DashboardMeta = {
    lastFetched: cat.lastFetched,
    swaggerUrl: cat.swaggerUrl,
    sourceTitle: cat.swagger.info?.title ?? "—",
    sourceVersion: cat.swagger.info?.version ?? "",
    totalEndpoints: totalOps,
    totalThemes: themeList.length,
    visibleThemes: themeList.filter((t) => !t.hidden).length,
    themes: themeList,
  };

  // Pass env config to client (no secrets — just public swagger URLs)
  const envs = getSwaggerEnvironments().map((e) => ({
    label: e.label,
    url: e.url,
  }));

  return (
    <DashboardClient
      meta={meta}
      refreshAction={refreshAction}
      environments={envs}
    />
  );
}
