/**
 * POST /api/parse
 * Accepts any supported API format and returns dashboard metadata + session ID.
 *
 * Body (JSON or FormData):
 *   format: "swagger" | "postman" | "graphql" | "har" | "curl"
 *   url?:   string (URL to fetch from)
 *   text?:  string (raw content — cURL commands or JSON string)
 *   file?:  File   (uploaded file — FormData only)
 */

import { NextResponse } from "next/server";
import { getParser, type SourceFormat, type ParseInput } from "@/lib/parsers";
import { generateSessionId, setCachedSource } from "@/lib/catalog/session-cache";
import { deriveThemes } from "@/lib/themes/registry";

export const dynamic = "force-dynamic";

export async function POST(request: Request) {
  try {
    let format: SourceFormat;
    let parseInput: ParseInput = {};

    const contentType = request.headers.get("content-type") ?? "";

    if (contentType.includes("multipart/form-data")) {
      const form = await request.formData();
      format = (form.get("format") as string) as SourceFormat;

      const url = form.get("url") as string | null;
      const text = form.get("text") as string | null;
      const file = form.get("file") as File | null;

      if (url) parseInput.url = url;
      if (text) parseInput.text = text;
      if (file) {
        const fileText = await file.text();
        try {
          parseInput.json = JSON.parse(fileText);
        } catch {
          parseInput.text = fileText;
        }
      }
    } else {
      const body = await request.json();
      format = body.format as SourceFormat;
      if (body.url) parseInput.url = body.url;
      if (body.text) parseInput.text = body.text;
      if (body.json) parseInput.json = body.json;
    }

    if (!format) {
      return NextResponse.json({ ok: false, error: "Missing 'format' field" }, { status: 400 });
    }

    const parser = getParser(format);
    const result = await parser.parse(parseInput);

    // Cache the parsed result
    const sid = generateSessionId();
    setCachedSource(sid, {
      swagger: result.swagger,
      baseUrl: result.baseUrl,
      sourceFormat: result.sourceFormat,
      sourceLabel: result.sourceLabel,
      lastFetched: new Date().toISOString(),
    });

    // Build meta (same shape as /api/meta)
    const themes = deriveThemes(result.swagger);
    let totalOps = 0;
    for (const item of Object.values(result.swagger.paths ?? {})) {
      if (!item) continue;
      for (const [m] of Object.entries(item)) {
        if (["get", "post", "put", "patch", "delete"].includes(m.toLowerCase())) {
          totalOps++;
        }
      }
    }

    const themeList = Object.values(themes).map((t) => ({
      key: t.key,
      title: t.title,
      description: t.description,
      sourceTags: t.tags,
      allowedMethods: t.allowedMethods,
      operationCount: t.operationCount,
      autoGenerated: t.autoGenerated,
      hidden: !t.exposeToVivi,
      schemaUrl: `/themes/${t.key}/openapi.json`,
    }));

    return NextResponse.json({
      ok: true,
      sid,
      sourceFormat: result.sourceFormat,
      sourceLabel: result.sourceLabel,
      lastFetched: new Date().toISOString(),
      swaggerUrl: result.baseUrl || `parsed:${result.sourceFormat}`,
      sourceTitle: result.swagger.info?.title ?? "—",
      sourceVersion: result.swagger.info?.version ?? "",
      totalEndpoints: totalOps,
      totalThemes: themeList.length,
      visibleThemes: themeList.filter((t) => !t.hidden).length,
      themes: themeList,
    });
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    return NextResponse.json({ ok: false, error: msg }, { status: 400 });
  }
}
