/**
 * lib/themes/registry.ts
 * --------------------------------------------------------------------------
 * Derives the resolved theme map from the source swagger at runtime.
 *
 * Default behavior: every unique tag in the swagger gets its own theme.
 * Optional overrides in config/theme-overrides.ts can rename keys, merge
 * tags, hide tags, or replace auto-generated descriptions.
 *
 * No theme list is hardcoded. Backend devs adding new tags need zero code
 * change here — refresh the cache and the new theme appears automatically.
 * --------------------------------------------------------------------------
 */

import type {
  HttpMethod,
  OperationObject,
  PathItem,
  SourceSwagger,
} from "../catalog/types";
import { TAG_OVERRIDES, type ThemeOverride } from "@/config/theme-overrides";

const HTTP_METHODS = new Set([
  "get",
  "post",
  "put",
  "patch",
  "delete",
  "options",
  "head",
  "trace",
]);

export interface ResolvedTheme {
  key: string;
  title: string;
  description: string;
  /** Source tags this theme bundles. */
  tags: string[];
  allowedMethods: HttpMethod[];
  triggers: string[];
  /** True if the theme should be listed for VIVI consumption. */
  exposeToVivi: boolean;
  /** True if the title or description was auto-generated rather than from override. */
  autoGenerated: boolean;
  /** Number of operations this theme covers. */
  operationCount: number;
}

interface TagOp {
  path: string;
  method: HttpMethod;
  op: OperationObject;
  tag: string;
}

function indexByTag(swagger: SourceSwagger): Record<string, TagOp[]> {
  const tagOps: Record<string, TagOp[]> = {};
  const paths = swagger.paths ?? {};
  for (const [pathStr, item] of Object.entries(paths)) {
    if (!item || typeof item !== "object") continue;
    for (const [method, op] of Object.entries(item as PathItem)) {
      if (!HTTP_METHODS.has(method.toLowerCase())) continue;
      const opObj = op as OperationObject;
      const tags = opObj.tags ?? ["_untagged_"];
      for (const tag of tags) {
        (tagOps[tag] ??= []).push({
          path: pathStr,
          method: method.toUpperCase() as HttpMethod,
          op: opObj,
          tag,
        });
      }
    }
  }
  return tagOps;
}

function slugify(s: string): string {
  return s
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2") // CamelCase → Camel-Case
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function autoDescribe(ops: TagOp[], tags: string[]): string {
  if (ops.length === 0) {
    return `Operations tagged ${tags.join(", ")}.`;
  }
  const summaries = Array.from(
    new Set(
      ops
        .map((o) => (o.op.summary || "").trim())
        .filter(Boolean),
    ),
  ).slice(0, 5);
  const tagPhrase = tags.join(" / ");
  if (summaries.length === 0) {
    return `${ops.length} operations under tag ${tagPhrase}.`;
  }
  return `${ops.length} operations under ${tagPhrase}, including: ${summaries.join("; ")}.`;
}

function defaultMethods(ops: TagOp[]): HttpMethod[] {
  const set = new Set<HttpMethod>();
  for (const o of ops) set.add(o.method);
  // Preserve a stable order
  const order: HttpMethod[] = ["GET", "POST", "PUT", "PATCH", "DELETE"];
  return order.filter((m) => set.has(m));
}

export function deriveThemes(swagger: SourceSwagger): Record<string, ResolvedTheme> {
  const tagOps = indexByTag(swagger);
  const allTags = Object.keys(tagOps).filter((t) => t !== "_untagged_");
  const themes: Record<string, ResolvedTheme> = {};
  const handledTags = new Set<string>();

  // Pass 1 — tags that have explicit overrides (to honor mergeTags)
  for (const tag of allTags) {
    if (handledTags.has(tag)) continue;
    const ovr: ThemeOverride | undefined = TAG_OVERRIDES[tag];
    if (!ovr) continue;
    if (ovr.hidden) {
      handledTags.add(tag);
      continue;
    }

    const mergedTags = [tag, ...(ovr.mergeTags ?? [])].filter((t) => allTags.includes(t));
    for (const t of mergedTags) handledTags.add(t);

    const ops = mergedTags.flatMap((t) => tagOps[t] ?? []);
    const key = ovr.key ?? slugify(tag);
    const title = ovr.title ?? `${tag} API`;
    const description = ovr.description ?? autoDescribe(ops, mergedTags);
    const allowedMethods = ovr.allowedMethods ?? defaultMethods(ops);

    themes[key] = {
      key,
      title,
      description,
      tags: mergedTags,
      allowedMethods,
      triggers: ovr.triggers ?? [],
      exposeToVivi: !ovr.hidden,
      autoGenerated: !ovr.title && !ovr.description,
      operationCount: ops.length,
    };
  }

  // Pass 2 — auto-themes for any tags not yet handled
  for (const tag of allTags) {
    if (handledTags.has(tag)) continue;
    const ops = tagOps[tag];
    const key = slugify(tag);
    themes[key] = {
      key,
      title: `${tag} API`,
      description: autoDescribe(ops, [tag]),
      tags: [tag],
      allowedMethods: defaultMethods(ops),
      triggers: [],
      exposeToVivi: true,
      autoGenerated: true,
      operationCount: ops.length,
    };
    handledTags.add(tag);
  }

  return themes;
}

export function visibleThemes(
  themes: Record<string, ResolvedTheme>,
): ResolvedTheme[] {
  return Object.values(themes).filter((t) => t.exposeToVivi);
}
