/**
 * lib/themes/registry.test.ts
 * Verify auto-derivation of themes from a fake swagger.
 */

import { test } from "node:test";
import { strict as assert } from "node:assert";
import { deriveThemes, visibleThemes } from "./registry";
import type { SourceSwagger } from "../catalog/types";

function makeSwagger(): SourceSwagger {
  return {
    openapi: "3.0.4",
    paths: {
      "/api/Membership/list": {
        get: { tags: ["Membership"], summary: "List members", responses: {} },
      },
      "/api/Membership/create": {
        post: { tags: ["Membership"], summary: "Create member", responses: {} },
      },
      "/api/AppUser/Login": {
        post: { tags: ["AppUser"], summary: "User login", responses: {} },
      },
      "/api/Communication/send": {
        post: { tags: ["Communication"], summary: "Send email", responses: {} },
      },
      "/api/Chat/post": {
        post: { tags: ["Chat"], summary: "Post chat message", responses: {} },
      },
      // Brand new tag the dev just added — no override exists for it
      "/api/NewFeature/do": {
        post: { tags: ["NewFeature"], summary: "Brand new endpoint", responses: {} },
      },
      "/api/MiddleWare/healthz": {
        get: { tags: ["MiddleWare"], summary: "Health", responses: {} },
      },
    },
  };
}

test("derived themes auto-cover untouched tags", () => {
  const t = deriveThemes(makeSwagger());
  // override-driven keys
  assert.ok(t.auth, "AppUser → auth via override");
  assert.equal(t.auth.title, "Authentication API");
  // pure auto: no override exists for NewFeature — gets a slugged key + auto-desc
  assert.ok(t["new-feature"], "NewFeature auto-themed at key 'new-feature'");
  assert.equal(t["new-feature"].title, "NewFeature API");
  assert.match(t["new-feature"].description, /Brand new endpoint/);
  assert.equal(t["new-feature"].autoGenerated, true);
});

test("merged tags combine into one theme; merged tag is hidden", () => {
  const t = deriveThemes(makeSwagger());
  assert.ok(t.communication, "Communication theme exists");
  assert.deepEqual(t.communication.tags.sort(), ["Chat", "Communication"]);
  // Chat is hidden separately, no duplicate theme
  assert.ok(!t.chat);
});

test("hidden tags don't produce themes", () => {
  const t = deriveThemes(makeSwagger());
  assert.ok(!t.middleware, "MiddleWare hidden by override");
});

test("visibleThemes filters out exposeToVivi=false", () => {
  const t = deriveThemes(makeSwagger());
  const v = visibleThemes(t);
  for (const th of v) assert.equal(th.exposeToVivi, true);
});

test("operation counts reflect merged + filtered tags", () => {
  const t = deriveThemes(makeSwagger());
  assert.equal(t.communication.operationCount, 2, "1 Communication + 1 Chat");
  assert.equal(t.auth.operationCount, 1);
  assert.equal(t["new-feature"].operationCount, 1);
});
