/**
 * app/api/meta/route.ts
 * GET /api/meta?url=... — JSON metadata used by the dashboard.
 * Supports dynamic swagger URL via ?url= query param.
 */

import { NextResponse } from "next/server";
import { resolveCatalog } from "@/lib/catalog/resolve";
import { deriveThemes } from "@/lib/themes/registry";

export const dynamic = "force-dynamic";

export async function GET(request: Request) {
  try {
    const cat = await resolveCatalog(request);
    const themes = deriveThemes(cat.swagger);

    let totalOps = 0;
    for (const item of Object.values(cat.swagger.paths ?? {})) {
      if (!item) continue;
      for (const [m] of Object.entries(item)) {
        if (["get", "post", "put", "patch", "delete"].includes(m.toLowerCase())) {
          totalOps++;
        }
      }
    }

    const themeList = Object.values(themes).map((t) => ({
      key: t.key,
      title: t.title,
      description: t.description,
      sourceTags: t.tags,
      allowedMethods: t.allowedMethods,
      operationCount: t.operationCount,
      autoGenerated: t.autoGenerated,
      hidden: !t.exposeToVivi,
      schemaUrl: `/themes/${t.key}/openapi.json`,
    }));

    return NextResponse.json({
      ok: true,
      lastFetched: cat.lastFetched,
      swaggerUrl: cat.swaggerUrl,
      sourceTitle: cat.swagger.info?.title ?? "—",
      sourceVersion: cat.swagger.info?.version ?? "",
      totalEndpoints: totalOps,
      totalThemes: themeList.length,
      visibleThemes: themeList.filter((t) => !t.hidden).length,
      themes: themeList,
    });
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    return NextResponse.json({ ok: false, error: msg }, { status: 502 });
  }
}
